services:
  groceries_schedule:
    build:
      context: .
    container_name: groceries_schedule
    volumes:
      - './../:/var/www'
      - './.ssh/:/root/.ssh'
      - '/var/www/docker'
    ports:
      - '1537:80'
      - '5173:5173'
      - '5174:5174'
      - '8000:8000'
    working_dir: /var/www
    environment:
      - DATABASE_HOST=groceries_schedule_db
      - DATABASE_PASS=myverystrongpassword
      - DATABASE_USER=root
  groceries_schedule_db:
    image: 'mysql:latest'
    container_name: groceries_schedule_db
    environment:
      - MYSQL_ROOT_PASSWORD=myverystrongpassword
    ports:
      - '3397:3306'
